spring:
  application:
    name: web-ui
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
app:
  backend:
    base-url: http://localhost:8080
  jwt:
    secret: ${JWT_SECRET}
    cookie-name: AUTH_TOKEN
    cookie-secure: false
