spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false
eureka:
  client:
    enabled: false
notification:
  messaging:
    enabled: false
cors:
  allowed-origins: http://localhost:8090
