server:
  port: 8888

spring:
  application:
    name: config-server
  output:
    ansi:
      enabled: always
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native