spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: animal-service-api
              uri: lb://animal-service
              predicates:
                - Path=/api/v1/shelters/**,/api/v1/species/**,/api/v1/breeds/**,/api/v1/animals/**
            - id: user-service-api
              uri: lb://user-service
              predicates:
                - Path=/api/v1/auth/**,/api/v1/users/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8080
